FROM 192.168.1.130:5000/onlyoffice:10

RUN \
rm /build_tools/make.py
ADD ./make.py /build_tools/make.py
RUN export onlyofficeautomate=2 && \
export onlyofficemake=3 && \
cd /build_tools/tools/linux && \
    python3 -u ./automate.py desktop
