FROM 192.168.1.130:5000/onlyoffice:1

RUN rm -v /build_tools/scripts/build.py
ADD ./scripts/build.py /build_tools/scripts/build.py

RUN \
export onlyofficepart=2 && \
cd ../../scripts && \
python -u -c "import base; base.replaceInFile(\"../config\", \"module=\\\"desktop builder server\\\"\", \"module=\\\"desktop\\\"\")" && \
cat ../config && \
cd ../tools/linux && \
mv -v /core/Common/3dParty/icu/linux_64 /core/Common/3dParty/icu/linux_arm64 && \
sh -c ./automate.py desktop
