FROM 192.168.1.130:5000/onlyoffice:1

RUN rm -v /build_tools/scripts/build.py /build_tools/make.py
ADD ./scripts/build.py /build_tools/scripts/build.py
ADD ./make.py /build_tools/make.py

RUN \
cd ../../scripts && \
python -uc "import os, base, shutil; base.download(\"https://cef-builds.spotifycdn.com/cef_binary_87.1.14%2Bga29e9a3%2Bchromium-87.0.4280.141_linuxarm64_minimal.tar.bz2\", \"cef_binary.tar.bz2\"); base.cmd(\"tar\",[\"-xvf\", \"cef_binary.tar.bz2\"]); os.remove(\"cef_binary.tar.bz2\"); base.cmd(\"cp\", [\"-rv\", \"cef_binary_87.1.14+ga29e9a3+chromium-87.0.4280.141_linuxarm64_minimal/Release/.\", \"/core/Common/3dParty/cef/linux_arm64/build/\"]); base.cmd(\"cp\", [\"-rv\", \"cef_binary_87.1.14+ga29e9a3+chromium-87.0.4280.141_linuxarm64_minimal/Resources/.\", \"/core/Common/3dParty/cef/linux_arm64/build/\"]); shutil.rmtree(\"cef_binary_87.1.14+ga29e9a3+chromium-87.0.4280.141_linuxarm64_minimal\")" && \
cd ../tools/linux && \
export onlyofficepart=2 && \
sh -c "./automate.py desktop"
