FROM 192.168.1.130:5000/onlyoffice:3

RUN rm -v /build_tools/make.py /build_tools/tools/linux/automate.py
ADD ./make.py /build_tools/make.py
ADD ./tools/linux/automate.py /build_tools/tools/linux/automate.py

RUN \
cd ../../scripts && \
python -u -c "import base; base.replaceInFile(\"../config\", \"module=\\\"desktop builder server\\\"\", \"module=\\\"desktop\\\"\")" && \
cd ../tools/linux && \
export onlyofficepart=4 && \
sh -c "./automate.py desktop"
