# Step 8
FROM bill88t/onlyoffice-layers:8
export onlyofficeautomate=2 && \
export onlyofficemake=2 && \
export onlyofficecommon=2 && \
cd /build_tools/tools/linux && \
    python3 -u ./automate.py desktop
    
# this is the current target
